set ANT_HOME=C:\Users\nsiva\Documents\Sivasenthil\MCS\Fall 2017\Enterprise Web Application\Tomcat\tomcat-7.0.34-preconfigured\apache-tomcat-7.0.34

set CLASSPATH= .;C:\Program Files\Java\jdk1.8.0_121\lib\mysql-connector-java-5.1.44-bin.jar;C:\Users\nsiva\Documents\Sivasenthil\MCS\Fall 2017\Enterprise Web Application\Tomcat\tomcat-7.0.34-preconfigured\apache-tomcat-7.0.34\lib\servlet-api.jar;C:\Users\nsiva\Documents\Sivasenthil\MCS\Fall 2017\Enterprise Web Application\Tomcat\tomcat-7.0.34-preconfigured\apache-tomcat-7.0.34\lib\jsp-api.jar;C:\Users\nsiva\Documents\Sivasenthil\MCS\Fall 2017\Enterprise Web Application\Tomcat\tomcat-7.0.34-preconfigured\apache-tomcat-7.0.34\lib\el-api.jar;C:\Users\nsiva\Documents\Sivasenthil\MCS\Fall 2017\Enterprise Web Application\Tomcat\tomcat-7.0.34-preconfigured\apache-tomcat-7.0.34\lib\commons-beanutils-1.8.3.jar;C:\Users\nsiva\Documents\Sivasenthil\MCS\Fall 2017\Enterprise Web Application\Tomcat\tomcat-7.0.34-preconfigured\apache-tomcat-7.0.34\lib\bson-3.0.4.jar;C:\Users\nsiva\Documents\Sivasenthil\MCS\Fall 2017\Enterprise Web Application\Tomcat\tomcat-7.0.34-preconfigured\apache-tomcat-7.0.34\lib\com.mysql.jdbc_5.1.5.jar;C:\Users\nsiva\Documents\Sivasenthil\MCS\Fall 2017\Enterprise Web Application\Tomcat\tomcat-7.0.34-preconfigured\apache-tomcat-7.0.34\lib\mongo-java-driver-3.5.0.jar;C:\Users\nsiva\Documents\Sivasenthil\MCS\Fall 2017\Enterprise Web Application\Tomcat\tomcat-7.0.34-preconfigured\apache-tomcat-7.0.34\lib\gson-2.6.2.jar;C:\Users\nsiva\Documents\Sivasenthil\MCS\Fall 2017\Enterprise Web Application\Tomcat\tomcat-7.0.34-preconfigured\apache-tomcat-7.0.34\lib\mail.jar;C:\Users\nsiva\Documents\Sivasenthil\MCS\Fall 2017\Enterprise Web Application\Tomcat\tomcat-7.0.34-preconfigured\apache-tomcat-7.0.34\lib\activation.jar

set CATALINA_HOME= C:\Users\nsiva\Documents\Sivasenthil\MCS\Fall 2017\Enterprise Web Application\Tomcat\tomcat-7.0.34-preconfigured\apache-tomcat-7.0.34

set TOMCAT_HOME= C:\Users\nsiva\Documents\Sivasenthil\MCS\Fall 2017\Enterprise Web Application\Tomcat\tomcat-7.0.34-preconfigured\apache-tomcat-7.0.34

set PATH="C:\Program Files\Java\jdk1.8.0_121";%PATH%

set JAVA_HOME= C:\Program Files\Java\jdk1.8.0_121